---
title: "Get BOM Stations"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, eval=TRUE}
library(httr)
library(dtplyr)
library(dplyr)
library(readr)
library(data.table)
library(stringi)
```

```{r import_stations, eval=TRUE}
regenerate_BOM_urls <- FALSE

bom_stations_raw <-
      readr::read_table(
        "ftp://ftp.bom.gov.au/anon2/home/ncc/metadata/lists_by_element/alpha/alphaAUS_3.txt",
        skip = 4,
        col_names = c("site",
                      "name",
                      "lat",
                      "lon"),
        col_types = readr::cols_only(
          "site" = readr::col_character(),
          "name" = readr::col_character(),
          "lat" = readr::col_double(),
          "lon" = readr::col_double()
        )
      )

fwrite(bom_stations, "bom_stations.csv")

bom_stations_by_url %>%
  mutate(Name = toupper(name)) %>%
  as.data.table %>%
  unique(by = "Name") %>%
  merge(bom_stations, by = "Name", all.y = TRUE) %>%
  as.data.table %>%
  # Only concerned with those still operating
  .[End == "May 2017" & is.na(url)]

nrow(bom_stations)


if (regenerate_BOM_urls) {
  get_BOM_data <- function(url, filename, write = FALSE) {
    out <-
      rjson::fromJSON(file = url) %>%
      use_series("observations") %>%
      use_series("data") %>%
      lapply(as.data.table) %>%
      rbindlist(use.names = TRUE, fill = TRUE)

    if (write) {
      out %>%
        fwrite(paste0("./bom/",
                      gsub("[^0-9]", "-", as.character(the_time)),
                      filename))
    }
  }

  # By cursory inspection, the varying part of the url runs from 90000 to 99999.
  # Idea here is to try to retrieve the JSON from each URL. Saving the result if
  # there is such a URL.
  name_by_url <- fread("./data-raw/name-by-url.csv")

  .closure <- function() {
    for (x in 90e3:100e3) {
      .first <- TRUE
      for (STATE in c("V", "N", "Q", "S", "W", "T", "D")) {
        for (y in c("60801", "60901", "60803", "60901", "60903")) {
          url <- paste0("http://www.bom.gov.au/fwo/ID", STATE, y, "/ID", STATE, y, ".", x, ".json")
          if (.first && (x %% 10) == 0) {
            # Poor man's progress bar
            cat(".")
            # if (.first && (x %% 1000) == 0) {
            #   cat("\n")
            # }
          }

          html_status <-
            HEAD(url = url) %>%
            status_code

          if (html_status != 404) {
            out <- rjson::fromJSON(file = url)
            if ("observations" %in% names(out)) {
              name <- out$observations$header[[1]]$name
              data.table(name = name,
                         url = url) %>%
                # append, noting to use unique() on the file later.
                fwrite("./data-raw/name-by-url.csv", append = TRUE)

            }
          }
        }

      }
      .first <- FALSE
    }
  }
  .closure()
}

name_by_url <-
  fread("./data-raw/name-by-url.csv") %>%
  .[url != "AAAA"] %>%
  .[!grepl("100000", url)] %>%
  .[order(url)] %>%
  .[, xx := as.integer(gsub("^.*\\.(9[0-9]{4})\\.json", "\\1", url))] %>%
  .[, row_id := 1:.N] %>%
  .[, xx_diff := c(NA, diff(xx))] %>%
  # unique(by = "xx", fromLast = TRUE) %>%
  .[, dup_url := duplicated(url)] %>%
  .[]

urls <- sum(!name_by_url$dup_url)

library(magrittr)

url_ok <- function(url) {
  HEAD(url = url) %>%
    status_code %>%
    equals(404) %>%
    not
}

name_by_url %<>%
  rowwise %>%
  mutate(url_ok = url_ok(url))

name_by_url %>%
  as.data.table %>%
  .[(url_ok)] %>%
  unique(by = c("name", "url")) %>%
  fwrite("./data-raw/name-by-url.csv")

current_bom_stations <-
  bom_stations %>%
  as.data.table %>%
  .[End == "May 2017", .(Name, Lat, Lon, Site)] %>%
  .[, NAME := toupper(Name)] %>%
  .[, NAME_NO_AIRPORT := gsub(" ((AIRPORT)|(AWS)|(AERO)|(AIRSTRIP))$", "", NAME)] %>%
  .[, .nomatch := TRUE]

uniqueDT <- function(...) data.table:::unique.data.table(...)

url_latlon_by_station_name <-
  fread("./data-raw/name-by-url.csv") %>%
  select(name, url) %>%
  as.data.table %>%
  unique %>%
  .[, NAME := toupper(name)] %>%
  merge(current_bom_stations, by = "NAME", all = TRUE) %>%
  .[, NAME_NO_AIRPORT := gsub(" ((AIRPORT)|(AWS)|(AERO)|(AIRSTRIP))$", "", toupper(name))] %>%
  .[, .nomatch := is.na(Lat)] %>%
  .[] %>%
  merge(current_bom_stations[, .(NAME, Lat, Lon, .nomatch)],
        by.x = c(".nomatch", "NAME_NO_AIRPORT"),
        by.y = c(".nomatch", "NAME"),
        all = TRUE) %>%
  .[, Lat := coalesce(Lat.x, Lat.y)] %>%
  .[, Lon := coalesce(Lon.x, Lon.y)] %>%
  .[, c("Lat.x", "Lat.y", "Lon.x", "Lon.y") := NULL] %>%
  .[] %>%
  merge(current_bom_stations[, .(NAME_NO_AIRPORT, Lat, Lon, .nomatch)],
        by.x = c(".nomatch", "NAME_NO_AIRPORT"),
        by.y = c(".nomatch", "NAME_NO_AIRPORT"),
        all = TRUE) %>%
  .[, Lat := coalesce(Lat.x, Lat.y)] %>%
  .[, Lon := coalesce(Lon.x, Lon.y)] %>%
  .[, c("Lat.x", "Lat.y", "Lon.x", "Lon.y") := NULL] %>%
  .[, .(NAME, name, url, Lat, Lon)] %>%
  .[!is.na(url)] %>%
  unique(by = "name") %T>%
  fwrite("JSONurl-latlon-by-station-name.csv") %>%
  .[]

# url_latlon_by_station_name %>%
#   filter(between(Lon, 135, 150),
#          between(Lat, -39, -34)) %>%
#   ggplot(aes(Lon, Lat, label = name)) +
#   geom_point() +
#   geom_text_repel() +
#   coord_map() +
#   theme_map()
```
